ramsey:
  mw:
    host: "https://api.setminusx.com"
  #    host: "http://localhost:8080"
  client:
    url: ${ramsey.mw.host}/api/ramsey/clients
    registration:
      phone-home:
        frequency-in-millis: 60000
  graph:
    url: ${ramsey.mw.host}/api/ramsey/graphs
  work-unit:
    queue:
      url: ${ramsey.mw.host}/api/ramsey/work-units
      fetch-size: 100
      publish-size: 50