ramsey:
  client:
    registration:
      url: "http://localhost:8080/api/ramsey/clients"
      phone-home:
        frequency-in-millis: 60000
  graph:
    url: "http://localhost:8080/api/ramsey/graphs"
  work-unit:
    queue:
      url: "http://localhost:8080/api/ramsey/work-units"
    fetch:
      size: 2