ramsey:
  client:
    url: "http://localhost:8080/api/ramsey/clients"
    registration:
      phone-home:
        frequency-in-millis: 60000
  graph:
    url: "http://localhost:8080/api/ramsey/graphs"
  work-unit:
    queue:
      url: "http://localhost:8080/api/ramsey/work-units"
      feeder:
        frequency-in-millis: 60000
        minimum-count: 50
        fetch-size: 100
      publish-size: 50