ramsey:
  mw:
#    host: "https://api.setminusx.com"
    host: "http://localhost:8080"
  client:
    url: ${ramsey.mw.host}/api/ramsey/clients
    registration:
      phone-home:
        frequency-in-millis: ${CLIENT_PHONE_HOME_FREQ:60000}
  graph:
    url: ${ramsey.mw.host}/api/ramsey/graphs
  work-unit:
    router:
      frequency-in-millis: ${WORK_UNIT_ROUTER_FREQ:60000}
    queue:
      url: ${ramsey.mw.host}/api/ramsey/work-units
      fetch-size: ${WORK_UNIT_FETCH_COUNT:100}
      publish-size: ${WORK_UNIT_PUBLISH_COUNT:50}
