logging:
  level:
    root: INFO
  pattern:
    level: "%clr([%X{X-B3-TraceId}]){blue} %clr(%5p){green}"

spring:
  main:
    web-application-type: none

ramsey:
  vertex-count: 288
  subgraph-size: 8