name: Perform Integration Tests

on:
  push:
    branches:
    - integration-test

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Maven Version Check
      run: mvn -v
    - name: Maven Integration Test
      run: mvn test -Dmaven-surefire-plugin.excludedGroups=none
